name: fetch-data

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      rt:
        description: 'rt'
        required: false
  repository_dispatch:
    types: [opened]
  schedule:
    - cron: "0 0 * * *" # https://docs.github.com/cn/actions/learn-github-actions/events-that-trigger-workflows

jobs:

  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
        ( cd cmd/refresh-data && go build -o /tmp/refresh-data ./cmd/refresh-data/main.go )

    - name: Run
      run: |
        /tmp/refresh-data

    - name: Commit and Push
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add --all
        git commit -am "Automated Commit: $(date)" || echo "no commit"
        git push || echo "no push"
